### ISSUE TITLE
Allow metadata OPTIONAL/REQUIRED mutation based on related metadata value

### ISSUE THREAD

**Issue by oesteban** [bids-standard/bids-validator#143]
I've screened currently open issues, and it could be the case that this is already encoded in the schema and I just don't know the semantics. Please let me know if this is not a current issue.

## The problem

In developing [BEP020 `bids-standard/bids-specification#1128`](https://github.com/bids-standard/bids-specification/pull/1128#discussion_r1916696816) we want to implement the following behavior in the schema:

When a `_physio.tsv.gz`'s corresponding sidecar contains the metadata `PhysioType` defined and set to  the vocabulary-controlled `"eyetrack"` term, then the physiological recordings annotated by that metadata are a "special" type of physio, with specific metadata keys and columns to represent eye-tracking data.

The problem is that, when you have eye-tracking, then some stimuli presentation metadata entries need to become MANDATORY, otherwise there's risk that eye-tracking data is not interpretable. The `StimulusPresentation` medatata dictionary can be defined in the `_events.json` file (weirdly, it's not a stimulus metadata file, but that's another topic).

As far as I know, there's no language in the schema to allow some fields of the `StimulusPresentation` dictionary to mutate from *recommended* to *required* in the presence of associated eye-tracking data corresponding to that particular run/experiment.

## An idea of potential solution?

In BEP020, I have proposed some jq-inspired language that could (possibly?) enable this, possibly added in the `src/schema/ruls/sidecars/events.yaml` file:

``` Yaml
StimulusPresentation_for_eyetracking:
  selectors:
    - suffix == "events"
    - (suffix == "physio").PhysioType == "eyetrack"
  fields:
    StimulusPresentation.ScreenDistance: required
    StimulusPresentation.ScreenOrigin: required
    StimulusPresentation.ScreenRefreshRate: recommended
    StimulusPresentation.ScreenResolution: required
    StimulusPresentation.ScreenSize: required
```

The idea would be to add a selector that queries another sidecar's metadata entry with `(suffix == "physio").PhysioType == "eyetrack"`.

## Conclusion

Unless I am outdated, it doesn't seem the above problem has been resolved. I'd like to help implement this in the schema, but I'm not sure where I should start or if it looks like a reasonable approach.

What do you think?

@effigies, @tsalo, @rwblair

cc/ @mszinte, @Remi-Gau

**Comment by effigies** [comment]
@oesteban Just seeing this now. This proposal would not make sense with our expression language. I would consider creating a new [association](https://github.com/bids-standard/bids-specification/blob/master/src/schema/meta/associations.yaml):

```yaml
physio:
  selectors:
    - 'task in entities'
    - extension != '.json'
  target:
    suffix: physio
    extension: .tsv.gz
  inherit: true
```

Then update the [context](https://github.com/bids-standard/bids-specification/blob/master/src/schema/meta/context.yaml):

```yaml
  associations:
    ...
    properties:
      physio:
        ...
        properties:
          path:
            description: 'Path to associated physio file'
            type: string
          sidecar:
            description: 'Sidecar metadata constructed via the inheritance principle'
            type: object
```

Then you would write your rule:

```yaml
StimulusPresentation_for_eyetracking:
  selectors:
    - suffix == "events"
    - associations.physio.sidecar.PhysioType == "eyetrack"
  fields:
    StimulusPresentation.ScreenDistance: required
    StimulusPresentation.ScreenOrigin: required
    StimulusPresentation.ScreenRefreshRate: recommended
    StimulusPresentation.ScreenResolution: required
    StimulusPresentation.ScreenSize: required
```
