### ISSUE TITLE
github action to run bids-validator on bids-examples

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-validator#38]
inspired by
- https://github.com/bids-standard/bids-validator/issues/1930

I think we should make it very easy for PRs against bids-specification, which change schema, to run validator using modified schema against target (or all) bids-examples. Originally I thought it should be just a matter of documentation:

- https://github.com/bids-standard/bids-validator/issues/1828

but I think we just need an action so we could just have 

```yaml
- uses: bids-standard/bids-validator@master
  with:
     bids-examples-glob: *
     schema-version: inplace
```

by default in `bids-specification` and make it active for any change to `src/schema`.

And then BEP PRs would gain possibility to point to a corresponding branch in bids-examples, e.g.

```yaml
- uses: bids-standard/bids-validator@master
  with:
     bids-examples-glob: *
     bids-examples-fork: yarikoptic/bids-examples
     bids-examples-branch: bep032
     schema-version: inplace
```

this would make it super easy to ensure that changes to schema are validated properly and hide away all needed intricacies of setting up/running bids-validator (#1930).
